// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrMLOIzKQ9ohXNOtu0MVGCwqihBywfdwo',
    appId: '1:582161759755:web:f08d036fdce4267906d10e',
    messagingSenderId: '582161759755',
    projectId: 'callkitexample-707b3',
    authDomain: 'callkitexample-707b3.firebaseapp.com',
    storageBucket: 'callkitexample-707b3.firebasestorage.app',
    measurementId: 'G-JC5NK743VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWHPYoiZhJHZAOpiGhhrkuzhBsw7c7s0E',
    appId: '1:582161759755:android:b5081d962b1f5e9706d10e',
    messagingSenderId: '582161759755',
    projectId: 'callkitexample-707b3',
    storageBucket: 'callkitexample-707b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsIJix7uPhDLJEcdPAoboTfe4HfovO-YM',
    appId: '1:582161759755:ios:8f7ef4a2893d826b06d10e',
    messagingSenderId: '582161759755',
    projectId: 'callkitexample-707b3',
    storageBucket: 'callkitexample-707b3.firebasestorage.app',
    iosBundleId: 'com.example.callkitExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsIJix7uPhDLJEcdPAoboTfe4HfovO-YM',
    appId: '1:582161759755:ios:8f7ef4a2893d826b06d10e',
    messagingSenderId: '582161759755',
    projectId: 'callkitexample-707b3',
    storageBucket: 'callkitexample-707b3.firebasestorage.app',
    iosBundleId: 'com.example.callkitExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrMLOIzKQ9ohXNOtu0MVGCwqihBywfdwo',
    appId: '1:582161759755:web:b751948ab86e178206d10e',
    messagingSenderId: '582161759755',
    projectId: 'callkitexample-707b3',
    authDomain: 'callkitexample-707b3.firebaseapp.com',
    storageBucket: 'callkitexample-707b3.firebasestorage.app',
    measurementId: 'G-R6HMYE13EM',
  );
}
